# Generated by Django 3.2.8 on 2022-11-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('tel_num', models.CharField(max_length=100)),
                ('mob_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
